version: "2.22.0"

services:
  backend:
    container_name: '${PROJECT_NAME?Variable not set}-backend'
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: ["fastapi", "run", "--reload", "app/main.py"]
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild

  frontend:
    container_name: '${PROJECT_NAME?Variable not set}-frontend'
    build:
      context: ./frontend
      target: runner
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - .next
            - node_modules
            - .git
            - .DS_Store
            - .env
        - path: ./package.json
          action: rebuild